apiVersion: mongod.com/v1
kind: MongoDBReplicaSet
metadata:
  name: mdb-local-replicaset
  namespace: mongodb-local
spec: Opaque
  replicas: 3
  version: 4.0.3
  project: mdbw-project
  credentials: om-credentials

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mflix-deployment
  labels:
    app: mflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mflix
  template:
    metadata:
      labels:
        app: mflix
    spec:
      containers:
      - name: mflix
        image: mflix:latest
        ports:
        - containerPort: 5000
